export const HOME = "/"
export const AUTENTICACAO = "/autenticacao"
export const AGENDAMENTO = "/agendamento"
export const CADASTRO = "/cadastro"
export const AUTENTICACADASTRO = "/autentica-cadastro"